
# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from="/SmartSAVER"
  to="smartsaver"

[[redirects]]
  from="/SmartSAVER/*"
  to="/smartsaver/:splat"

[[redirects]]
  from="/SMARTSAVER"
  to="/smartsaver"

[[redirects]]
  from="/SMARTSAVER/*"
  to="/smartsaver/:splat"

[[redirects]]
  from="/SmartSAVER/Survey"
  to="/smartsaver/survey"

[[redirects]]
  from="/Saver"
  to="/saver"

[[redirects]]
  from="/YWCA"
  to="ywca"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  #[dev] 
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
  